import Image from "next/image";

// The app icon (generated by scripts/make-icon.py), shown small in the header.
export function Logo({ size = 34 }: { size?: number }) {
  return <Image src="/brand/icon-128.png" alt="" width={size} height={size} priority className="shrink-0" />;
}
